name: saltstack-keepalived-formula
source: https://github.com/bechtoldt/saltstack-keepalived-formula
summary: SaltStack Formula to set up and configure keepalived, a router and loadbalancer based on VRRP
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
